CREATE DATABASE BELMONT_HACKATHON;

USE DATABASE BELMONT_HACKATHON;

CREATE STAGE MUSIC_GENRE;
CREATE STAGE MUSIC_FEATURES;
CREATE STAGE MUSIC_MENTAL_HEALTH;
CREATE STAGE MUSIC_LYRICS;
CREATE STAGE MUSIC_CAPTIONS;
CREATE STAGE MUSIC_POPULARITY;

CREATE STAGE LYRICS
 ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
CREATE STAGE MENTAL_HEALTH
 ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
CREATE STAGE POPULARITY
 ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
CREATE STAGE GENRE
 ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
CREATE STAGE FEATURES
 ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE WAREHOUSE BELMONT_HACKATHON_WH WITH
  WAREHOUSE_SIZE = MEDIUM
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;
