CREATE DATABASE BELMONT_HACKATHON;

CREATE STAGE MUSIC_GENRE;
CREATE STAGE MUSIC_FEATURES;
CREATE STAGE MUSIC_MENTAL_HEALTH;
CREATE STAGE MUSIC_LYRICS;
CREATE STAGE MUSIC_CAPTIONS;
CREATE STAGE MUSIC_POPULARITY;

CREATE STAGE LYRICS;
CREATE STAGE MENTAL_HEALTH;
CREATE STAGE POPULARITY;
CREATE STAGE GENRE;
CREATE STAGE FEATURES;
